# Generated by Django 3.0.7 on 2020-08-13 12:08

from django.db import migrations, models
import django.db.models.deletion
import vault.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=253)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labels', models.ManyToManyField(related_name='secret_notes', to='sor.Label')),
            ],
        ),
        migrations.CreateModel(
            name='SecretLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=253)),
                ('username', models.CharField(max_length=253)),
                ('password', vault.fields.EncryptedCharField(max_length=253)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labels', models.ManyToManyField(related_name='secret_logins', to='sor.Label')),
            ],
        ),
        migrations.CreateModel(
            name='SecretItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=253)),
                ('name', models.CharField(max_length=253)),
                ('value', models.CharField(max_length=253)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labels', models.ManyToManyField(related_name='secret_items', to='sor.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=253)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_login', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='vault.SecretLogin')),
            ],
        ),
    ]
