name: CI Build

on:
  push:
    branches: [master]

jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        working-directory: ./bedrock
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        working-directory: ./bedrock
        run: |
          python manage.py test --settings=config.settings_tests
  build-develop:
    name: Build Develop
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx 1
        uses: docker/setup-buildx-action@v1
        id: builder1

      - name: Set up Docker Buildx 2
        uses: docker/setup-buildx-action@v1
        id: builder2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build develop
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
          target: target1
          context: ./bedrock
          file: ./deployment/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: sajalshres/bedrock:develop

      - name: Build latest
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder2.outputs.name }}
          target: target2
          context: ./bedrock
          file: ./deployment/Dockerfile.prod
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: sajalshres/bedrock:latest
